services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      PROMPTIC_DEBUG: ${PROMPTIC_DEBUG}
    volumes:
      - pdf_to_podcast_gradio:/app/.gradio
      - pdf_to_podcast_gradio_cache:/app/gradio_cached_examples
      - ./pdf_to_podcast_storage:/app/podcast_storage

volumes:
  pdf_to_podcast_gradio:
  pdf_to_podcast_gradio_cache:
